### ISSUE TITLE
Deployment not working

### ISSUE THREAD

**Issue by cwash05** [Azure/prometheus-collector#382] opened 2023-02-10 19:34 UTC
There seems to be an issue with the bicep files.  running them as is returns errors and the deployment fails.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/23502916/217825547-f0dfba4e-6b82-469c-8865-ebc8e4f6f8c2.png">

Looks like there is an extra '}' at the end of the resource names. 
{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "The alert rule name can’t contain the following characters: @ / # % & + * < > ? : \\ { } Activity ID: ec76a6b0-6e8b-46bd-b60c-856a01be59cb."
    }
}

i changed the cluster name from var to a param and added to the params file. 
the dashboard was created but the link to the cluster is broken

<img width="514" alt="image" src="https://user-images.githubusercontent.com/23502916/217878459-55bf15d6-b020-4ff7-9745-1cb675b6bed7.png">

It was also missing the prem for the dashboard id on the AMW. added that but it didn't fix the broken link.

this resource class 'Microsoft.ContainerService/managedClusters/providers/dataCollectionRuleAssociations@2021-09-01-preview', in the nested_azuremonitormetrics_dcra_clusterResourceId.bicep file doesn't exit.   Replaced it with Microsoft.Insights/dataCollectionRuleAssociations@2021-09-01-preview, but still not getting the cluster connection. 

<img width="790" alt="image" src="https://user-images.githubusercontent.com/23502916/218164526-36a73b06-b53e-41fa-9162-5ceeb9b3b0c5.png">

(had to add the 'existing' to get the cluster scope)

This is compared to running the update command from the cli

az aks update --enable-azuremonitormetrics -n $aksName -g $aksResourceGroupName --azure-monitor-workspace-resource-id $azMonWorkspaceId  --grafana-resource-id $grafanaDashboardId

I think the main issue is with the MSProm name.  When I hard coded EUS, the short name for eastus it finally worked (with all the previous changes intact).  
<img width="253" alt="image" src="https://user-images.githubusercontent.com/23502916/218164916-d693a0de-2de8-48d3-8e45-3ea5a29da9cf.png">

and I found no API that would return the short name. I just got the EUS from previous command line runs

The last thing is, it's not recognizing the Windows node pools.  This is even true when turning on from the cli.  I know there's a Windows node exporter, I assume it should be installed when you have Windows node pools.  This is W2022, did not try with W2019
They do at least show up on the Kubernetes / Compute Resources / Node (Pods) dashboard, but with no data

![image](https://user-images.githubusercontent.com/23502916/218167676-8f3e2f0c-899a-41f0-ac1e-7d6e21e10129.png)

Actually one more thing.  A few weeks back, you would also get dashboards for Azure Monitor Container Insights

<img width="277" alt="image" src="https://user-images.githubusercontent.com/23502916/218165743-d50e2edd-7b91-4278-b4d8-62014f0d53c8.png">

That's no longer happening even when the insights is enabled for the cluster. 

The two questions I have are
1. How do we get the Windows servers supported?
2. How do we get the Azure Monitor Container Insights dashboard's back.

**Comment by gracewehner** [comment] 2023-02-10 23:11
Hi @cwash05, thanks for your feedback. @Sohamdg081992, would you be able to look at the bicep issues mentioned? @cwash05 in the meantime, could you please try with the [ARM template deployment](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/prometheus-metrics-enable?tabs=resource-manager) if you are blocked?

1. Windows support is currently in progress. If you are internal to Microsoft, you can reach out to us at ciprometheus@microsoft.com, and we can see if we can include you in a private preview.

2. For the Azure Monitor Container Insights dashboards, these are the 1P private preview dashboards that are now deprecated and were recently removed. The Managed Prometheus dashboards replace these and use the recording rules included in the new addon (non-helm chart) public preview setup. If you are looking for the additional dashboards that were included in the original folder, please see the instructions [here](https://github.com/Azure/prometheus-collector/blob/main/GeneratedMonitoringArtifacts/non-default/README.md).

**Comment by cwash05** [comment] 2023-02-14 03:41
@gracewehner I do have one other question, how can we get the short names for the regions?  I can't seem to find API/query that will return them.

**Comment by Sohamdg081992** [comment] 2023-02-14 06:01
@cwash05 I will update you shortly on this.

**Comment by Sohamdg081992** [comment] 2023-02-14 22:43
Hi @cwash05 , could you please let us know the commands and the steps you have taken? I tried but could not reproduce your scenario.  Have you followed the steps and commands in the README [file](https://github.com/Azure/prometheus-collector/tree/main/AddonBicepTemplate)?

 I followed the steps in the README [file](https://github.com/Azure/prometheus-collector/tree/main/AddonBicepTemplate). I do not see the extra '}' in the resource names and metrics are flowing through Grafana. Below are screenshots. Also the command I use to deploy is the one mentioned in the above readme file(not the one which you have mentioned). 
Also no short names are required in the MSProm name as you can find in the below screenshots. The role assignment also got attached without any modification.

<img width="1871" alt="deployment" src="https://user-images.githubusercontent.com/31517098/218879565-6f9cf813-0638-499d-be18-c51d94d383f3.png">


<img width="1844" alt="Grafana" src="https://user-images.githubusercontent.com/31517098/218879766-8b214c23-3ad7-4995-b88f-181e8c2bfe20.png">

**Comment by cwash05** [comment] 2023-02-15 22:14
@Sohamdg081992 now i can't reproduce it.  Not getting the 

"code": "BadRequest",
"message": "The alert rule name can’t contain the following characters: @ / # % & + * < > ? : \ { } Activity ID: ec76a6b0-6e8b-46bd-b60c-856a01be59cb."

error anymore.  The only thing that is different is that i upgraded my version of bicep????

**Comment by Sohamdg081992** [comment] 2023-02-15 23:05
I am not sure but it might be related to that. I never got this error while developing. Which bicep version did you upgrade from?

**Comment by Sohamdg081992** [comment] 2023-02-16 21:54
Since this issue is not happening anymore after upgrading bicep version, is it okay to close this issue?

**Comment by cwash05** [comment] 2023-02-17 13:55
@Sohamdg081992 should the node exporter work with Mariner?

**Comment by gracewehner** [comment] 2023-02-21 18:52
@cwash05 the node exporter should work with Mariner. Are you seeing issues?

**Comment by cwash05** [comment] 2023-02-22 19:21
@gracewehner, yes.  when i run the FullAzureMonitorMetricsProfile.bicep as a module in a larger bicep or when i call it in a script as a separate template, the node exporter dashboard are not always populated.  
ie
working: https://profana690-dashboard-eqbpeygvbje3bjcr.eus.grafana.azure.com/d/D4pVs6738/node-exporter-nodes?orgId=1&refresh=30s

notworking: https://grafpro303-dashboard-crd5d7g4h4bsc9e3.eus.grafana.azure.com/d/t5aja6738/node-exporter-use-method-node?orgId=1&refresh=1m

at first i thought maybe it was when the amw/cluster/grafana where not in the same regions, but both of these are fully deployed to east us. 

both ran from the same aksdeploy.sh script. 
[https://github.com/cwash05/aks/archive/refs/heads/base-agic.zip](https://github.com/cwash05/aks/archive/refs/heads/base-agic.zip)

it's the base-cluster folder

**Comment by gracewehner** [comment] 2023-02-22 21:16
Hi @cwash05 thanks for the access to the dashboards. For the working cluster, I see the up metric is 1 for the node job, but for the not working one, up=0 for the node job. This means there is some issue with scraping the node exporter targets on that cluster. The logs of the prometheus-collector container on the ama-metrics-node-* pod should show more why the scrape is failing. Please ping me on teams if the error in the logs does not help, and we can have a call.

**Closed** 2023-03-16 10:35 UTC
Labels: no-issue-activity
